name: Deploy to EC2 on Push Check

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AWS_EC2_INSTANCE_IP }} << 'EOF'
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          git clone git@github.com:kapilarathnayaka/gicassesmentfullstack.git || (cd gicassesmentfullstack && git pull)
          ls -la gicassesmentfullstack
          cd gicassesmentfullstack/CafeEmployeeBackend
          docker build -t gic-test-image .
          docker run -d -p 8080:80 gic-test-image
          EOF
