name: Deploy to EC2 on Push Check

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SSH to EC2 and deploy Docker
        run: |
          # Install SSH client and AWS CLI on the runner if not already available
          sudo apt-get install -y openssh-client
          # Set up SSH agent and key
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Disable strict host key checking to avoid SSH warnings
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config
          # SSH to EC2 instance and deploy the Docker container
          ssh -o StrictHostKeyChecking=no ec2-user@${{secrets.AWS_EC2_INSTANCE_IP}} << 'EOF'
            # Clone the repository if it doesn't exist already
          if [ ! -d "/home/ec2-user/gicassesmentfullstack" ]; then
            git clone https://github.com/kapilarathnayaka/gicassesmentfullstack.git /home/ec2-user/gicassesmentfullstack
          else
          # Navigate to the directory and pull the latest changes if the repo already exists
            cd /home/ec2-user/gicassesmentfullstack
            git pull origin main
          fi
          # Navigate to the backend folder
            cd /home/ec2-user/gicassesmentfullstack/CafeEmployeeBackend
          # Build the Docker image using the Dockerfile inside the folder
            docker build -t gic-test-image -f Dockerfile .
          # Run the Docker container in detached mode and map ports
            docker run -d -p 8080:80 gic-test-image
          EOF
